apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: auth
type: Opaque
data:
  root-pass: bXlzcWwtcm9vdC1wYXNz # base64 for mysql-root-pass
  mysql-db: d2VhdGhlcmFwcA==
  mysql-user: YWRtaW51c2Vy 
  mysql-pass: YWRtaW5wYXNzd29yZA==
  secert-key: eGNvMHNyMGZoNGU1MngwM2c5bXY=