apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bXlzcWwtcm9vdC1wYXNz # base64 for mysql-root-pass
  MYSQL_DATABASE: d2VhdGhlcmFwcA==
  MYSQL_USER: YWRtaW51c2Vy 
  MYSQL_PASSWORD: YWRtaW5wYXNzd29yZA==


# you can do this or doing manual way by using job to configure DB 